---
title: Date Tracker
timezone: America/New_York
collections:
  dates:
    title: Dates
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: dates
  values:
    title: ''
    description: ''
    event_date: ''
    display_image: ''
email: tylergaugler16@gmail.com
description: Date Tracker App
baseurl:
url:
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
